name = "gtin"
version = "1.0.0"
description = "A Gleam library for validating and generating GTIN (Global Trade Item Number) codes according to GS1 specification."
licenses = ["MIT"]
repository = { type = "github", user = "kickinespresso", repo = "gtin" }
links = [
  { title = "Home page", href = "https://github.com/kickinespresso/gtin" },
  { title = "Hex", href = "https://hex.pm/packages/gtin" },
  { title = "Documentation", href = "https://hexdocs.pm/gtin/" }
]

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
